Web.ERP/ViewModels/ErrorViewModel.cs
namespace Web.ERP.ViewModels
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Web.ERP/ViewModels/RoleViewModel.cs
using DominCore.IServices;
using System.ComponentModel.DataAnnotations;

namespace Web.ERP.ViewModels
{
    public class RoleViewModel
    {
        public List<RoleModel> Roles { get; set; } = new();
        public RoleModel NewRole { get; set; } = new();
    }
    public class RoleModel
    {

        public string? RoleId { get; set; }
        [Display(Name = "lbRoleName")]
        [Required(ErrorMessage ="lbEnter.RoleName")]
        public string RoleName { get; set; } = string.Empty;
    }
}

Web.ERP/Controllers/AccountsController.cs
using DominCore.Constants;
using DominCore.IServices;
using Microsoft.AspNetCore.Mvc;
using Web.ERP.Languages;

namespace Web.ERP.Controllers
{
    public class AccountsController : Controller
    {

        private readonly IServices<RoleModel> _servicesRole;
        private readonly ResourceWebServices _Loc;
        public AccountsController(IServices<RoleModel> servicesRoleModel, ResourceWebServices loc)
        {
            _servicesRole = servicesRoleModel;
            _Loc = loc;
        }
        public async Task<IActionResult> Roles()
        {
            return View(new RoleViewModel
            {
                Roles = await _servicesRole.GetAll(),
                NewRole = new RoleModel()
            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SavRole(RoleViewModel model)
        {
            if (!ModelState.IsValid)
                return NotFound();
            //save
            if(model.NewRole.RoleId is null)
            {
                if (await _servicesRole.RoleExistsAsync(model.NewRole))
                {
                    SessionMsg(Helper.Error, _Loc["lbNot.RoleExists"]);
                    return RedirectToAction(nameof(Roles));
                }
                if (await _servicesRole.Save(model.NewRole))
                    SessionMsg(Helper.Success, _Loc["lb.Accounts.Roles.Saved"]);
                else
                    SessionMsg(Helper.Error,_Loc["lbNotSaved.GroupRole"]);
            }

            else //Edit
            {
                if (await _servicesRole.Save(model.NewRole))
                    SessionMsg(Helper.Success , _Loc["lbUpdate.GroupRole"]);
                else
                    SessionMsg(Helper.Error , _Loc["lbNotUpdate.GroupRole"]);
            }
            return RedirectToAction(nameof(Roles));


        }
        public async Task<IActionResult> DeleteRole(string Id)
        {
            if (await _servicesRole.Delete(Id))
                return RedirectToAction(nameof(Roles));
            return RedirectToAction(nameof(Roles));
        }
        public async Task<IActionResult> DeleteRoleSelected(List<string> Selected )
        {
            if (Selected.Count()>0)
            
                foreach (var item in Selected)
                    await _servicesRole.Delete(item);
             return RedirectToAction(nameof(Roles));
            
        }
        private void SessionMsg(string MsgType,string Msg)
        {
            HttpContext.Session.SetString(Helper.msgType, MsgType);
            HttpContext.Session.SetString(Helper.msg, Msg);
        }


    }
}

Web.ERP/Controllers/HomeController.cs
namespace Web.ERP.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Web.ERP/Controllers/LanguagesController.cs
using Microsoft.AspNetCore.Localization;

namespace Web.ERP.Controllers
{
    public class LanguagesController : Controller
    {
        [HttpPost]//methode of select language //culture is selected language // returnUrl when we reload page 
        public IActionResult SelectLanguage(string culture, string returnUrl)
        {
            Response.Cookies.Append(CookieRequestCultureProvider.DefaultCookieName,
                CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
                new CookieOptions { Expires=DateTimeOffset.UtcNow.AddYears(1)});
            return LocalRedirect(returnUrl);
        }
    }
}

Web.ERP/Views/Accounts/Roles.cshtml
@using DominCore.Constants;
@model RoleViewModel;
@{
    ViewData["Title"] = "Roles";
}


<div class="content-header row">
    <div class="content-header-left col-md-9 col-12 mb-2">
        <div class="row breadcrumbs-top">
            <div class="col-12">
                <h2 class="content-header-title float-left mb-0"></h2>
                <div class="breadcrumb-wrapper col-12">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item">
                            <a href="/">@Loc["lbHome"]</a>
                        </li>
                        <li class="breadcrumb-item active">
                            @Loc["lbGroupRole"]
                        </li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
</div>






<!-- users list start -->
<section class="users-list-wrapper">
</section>
<!-- Data list view starts -->
<section id="data-list-view" class="data-list-view-header">
    <form asp-controller="Accounts" asp-action="DeleteRoleSelected" id="Submit-Form">

        <div class="action-btns">
            <div class="btn-dropdown d-inline mr-1 mb-1">
                <div class="btn-group dropdown actions-dropodown">
                    <button type="button" class="btn btn-info action-add Reset">
                        <i class="feather icon-plus"> </i> @Loc["lbbtnSave"]
                    </button>
                    &nbsp;
                    <button type="button"
                            class="btn btn-primary px-1 py-1 dropdown-toggle waves-effect waves-light"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        @Loc["lbProcedures"]
                    </button>
                    <div class="dropdown-menu">
                        <button class="dropdown-item text-danger" id="btn-DeleteAll" type="submit"><i class="feather icon-trash"></i>@Loc["lbDelete"]</button>
                    </div>

                </div>
            </div>
        </div>


        <!-- DataTable starts -->
        <div class="table-responsive" style="margin-top:-25px ">
            <table class="table data-list-view ">
                <thead>
                    <tr>
                        <td>
                            <fieldset class="checkbox">
                                <div class="vs-checkbox-con vs-checkbox-primary">
                                    <input type="checkbox" id="selectAll">
                                    <span class="vs-checkbox">
                                        <span class="vs-checkbox--check">
                                            <i class="vs-icon feather icon-check"></i>
                                        </span>
                                    </span>
                                </div>
                            </fieldset>
                        </td>
                        <th>@Loc["lbRoleName"]</th>
                        <th>@Loc["lbEvents"]</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var role in Model.Roles)
                    {

                        <tr>
                            <td>
                                <fieldset class="checkbox">
                                    <div class="vs-checkbox-con vs-checkbox-primary">
                                        <input type="checkbox" value="@role.RoleId" name="Selected">

                                        <span class="vs-checkbox">
                                            <span class="vs-checkbox--check">
                                                <i class="vs-icon feather icon-check"></i>
                                            </span>
                                        </span>
                                    </div>
                                </fieldset>
                            </td>


                            @switch (role.RoleName)
                            {
                                case Helper.FullOwner:
                                    <td>
                                        <div class="chip chip-danger w-75">
                                            <div class="chip-body">
                                                <div class="chip-text">@role.RoleName</div>
                                            </div>
                                        </div>
                                    </td>
                                    break;

                                case Helper.OwnerCompany:
                                    <td>
                                        <div class="chip chip-info w-75">
                                            <div class="chip-body">
                                                <div class="chip-text">@role.RoleName</div>
                                            </div>
                                        </div>
                                    </td>
                                    break;

                                case Helper.BranchManager:
                                    <td>
                                        <div class="chip chip-success w-75">
                                            <div class="chip-body">
                                                <div class="chip-text">@role.RoleName</div>
                                            </div>
                                        </div>
                                    </td>
                                    break;
                                default:
                                    <td>
                                        <div class="chip chip-warning w-75">
                                            <div class="chip-body">
                                                <div class="chip-text">@role.RoleName</div>
                                            </div>
                                        </div>
                                    </td>
                                    break;
                            }

                            <td class="product-action">
                                <!-- Button trigger modal -->

                                <a class="action-edit" href="#" onclick="onEdit(@Model.Roles.IndexOf(role))"><i class="feather icon-edit"></i></a>

                                <a class="action-delete" href="#" onclick="onDelete('@role.RoleId')">
                                    <i class="feather icon-trash"></i>
                                </a>
                            </td>
                        </tr>

                    }


                </tbody>
            </table>
        </div>
        <!-- DataTable ends -->
    </form>
    <!-- add new sidebar starts -->
    <div class="add-new-data-sidebar">
        <div class="overlay-bg"></div>
        <div class="add-new-data">
            <div class="div mt-2 px-2 d-flex new-data-title justify-content-between">
                <div>
                    <h4 class="text-uppercase">@Loc["lbAddGroupRole"]</h4>
                </div>
                <div class="hide-data-sidebar">
                    <i class="feather icon-x"></i>
                </div>
            </div>

            <form asp-controller="Accounts" asp-action="SavRole" method="post">


                <div class="data-items pb-3">
                    <div class="data-fields px-2 mt-3">
                        <div class="row">
                            <input hidden asp-for="NewRole.RoleId" id="roleId" />
                            <div class="col-sm-12 data-field-col">
                                <label asp-for="NewRole.RoleName"></label>
                                <input asp-for="NewRole.RoleName" class="form-control" id="roleName" />
                                <span asp-validation-for="NewRole.RoleName" class="text-danger"></span>
                            </div>

                        </div>
                    </div>
                </div>
                <div class="add-data-footer d-flex justify-content-around px-3 mt-2">
                    <div class="add-data-btn">
                        <button type="submit" class="btn btn-primary">@Loc["lbbtnSave"]</butto>
                    </div>
                    <div class="cancel-data-btn">
                        @* <button class="btn btn-outline-danger">الغاء</button>*@
                        <a class="btn btn-outline-danger">@Loc["lbCancel"]</a>
                       
                    </div>
                </div>
            </form>
        </div>
    </div>
    <!-- add new sidebar ends -->
</section>
<!-- Data list view end -->
@section Scripts{
   
    @if (!string.IsNullOrEmpty(Context.Session.GetString(Helper.msgType)))
    {
        if (Context.Session.GetString(Helper.msgType) == Helper.Success)//lw mch fdya htd5ol 3la if tanya de
        {
            <script>
                toastr.success('@Html.Raw(Context.Session.GetString(Helper.msg))', '@Loc["lbSave"]');
            </script>
        }
        else
        {
            <script>
                toastr.error('@Html.Raw(Context.Session.GetString(Helper.msg))', '@Loc["lbNotSaved"]');
            </script>
        }
        Context.Session.SetString(Helper.msgType ,"");
    }

    <script src="~/Modules/Roles.js"></script>
    <partial name="_ValidationScriptsPartial"/>
    <script>

        let roles = @Html.Raw(Json.Serialize(Model.Roles));
    </script>
}

Web.ERP/Views/Shared/_Footer.cshtml
  <!-- BEGIN: Footer-->
<footer class="footer footer-static footer-light">
    <p class="clearfix blue-grey lighten-2 mb-0">
        <span class="float-md-left d-block d-md-inline-block mt-25">
            COPYRIGHT &copy; 2020<a class="text-bold-800 grey darken-2" href="https://1.envato.market/pixinvent_portfolio"
                                    target="_blank">Pixinvent,</a>All rights Reserved
        </span><span class="float-md-right d-none d-md-block">
            Hand-crafted & Made with<i class="feather icon-heart pink"></i>
        </span>
        <button class="btn btn-primary btn-icon scroll-top" type="button">
            <i class="feather icon-arrow-up"></i>
        </button>
    </p>
</footer>
<!-- END: Footer-->

Web.ERP/Views/Shared/_Header.cshtml
@using System.Globalization;
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0,
                minimal-ui" />
    <meta name="description" content="Erp admin is super flexible, powerful, clean &amp; modern
                responsive bootstrap 4 admin template with unlimited possibilities." />
    <meta name="keywords" content="admin template, Erp admin template, dashboard template,
                flat admin template, responsive admin template, web app" />
    <meta name="author" content="PIXINVENT" />
    <title>ERP System</title>
    <link rel="apple-touch-icon" href="~/app-assets/images/ico/apple-icon-120.png" />
    <link rel="shortcut icon" type="image/x-icon" href="~/~/app-assets/images/ico/favicon.ico" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/tabler/icons@latest/iconfont/tabler-icons.min.css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,500,600" rel="stylesheet" />

    @if(CultureInfo.CurrentCulture.Name.StartsWith("ar"))
    {
        <!-- BEGIN: Vendor CSS-->
        <link rel="stylesheet" type="text/css" href="~/app-assets/vendors/css/vendors-rtl.min.css" />
        <link rel="stylesheet" type="text/css" href="~/app-assets/vendors/css/extensions/toastr.css">
        <link rel="stylesheet" type="text/css" href="~/app-assets/vendors/css/tables/datatable/datatables.min.css">
        <link rel="stylesheet" type="text/css" href="~/app-assets/vendors/css/tables/datatable/responsive.dataTables.min.css">
        <link rel="stylesheet" type="text/css" href="~/app-assets/vendors/css/tables/datatable/rowReorder.dataTables.min.css">
        <link rel="stylesheet" type="text/css" href="~/app-assets/vendors/css/tables/ag-grid/ag-grid.css" />
        <link rel="stylesheet" type="text/css" href="~/app-assets/vendors/css/tables/ag-grid/ag-theme-material.css" />
        <link rel="stylesheet" type="text/css" href="~/app-assets/vendors/css/tables/datatable/extensions/dataTables.checkboxes.css">


        <!-- END: Vendor CSS-->
        <!-- BEGIN: Theme CSS-->
        <link rel="stylesheet" type="text/css" href="~/app-assets/css-rtl/bootstrap.css" />
        <link rel="stylesheet" type="text/css" href="~/app-assets/css-rtl/bootstrap-extended.css" />
        <link rel="stylesheet" type="text/css" href="~/app-assets/css-rtl/colors.css" />
        <link rel="stylesheet" type="text/css" href="~/app-assets/css-rtl/components.css" />
        <link rel="stylesheet" type="text/css" href="~/app-assets/css-rtl/themes/dark-layout.css" />
        <link rel="stylesheet" type="text/css" href="~/app-assets/css-rtl/themes/semi-dark-layout.css" />

        <!-- BEGIN: Page CSS-->
        <link rel="stylesheet" type="text/css" href="~/app-assets/css-rtl/plugins/extensions/toastr.css">
        <link rel="stylesheet" type="text/css" href="~/app-assets/css-rtl/core/menu/menu-types/vertical-menu.css">
        <link rel="stylesheet" type="text/css" href="~/app-assets/css-rtl/core/colors/palette-gradient.css">
        <link rel="stylesheet" type="text/css" href="~/app-assets/css-rtl/pages/app-user.css" />
        <link rel="stylesheet" type="text/css" href="~/app-assets/css-rtl/pages/aggrid.css" />
        <link rel="stylesheet" type="text/css" href="~/app-assets/css-rtl/plugins/file-uploaders/dropzone.css">
        <link rel="stylesheet" type="text/css" href="~/app-assets/css-rtl/pages/data-list-view.css">
        <!-- END: Page CSS-->
        <!-- BEGIN: Custom CSS-->
        <link rel="stylesheet" type="text/css" href="~/app-assets/css-rtl/custom-rtl.css" />
        <link rel="stylesheet" type="text/css" href="~/assets/scss/style-rtl.css" />
         <!-- END: Custom CSS-->
         }

    else
    {
    <!-- BEGIN: Vendor CSS-->
    <link rel="stylesheet" type="text/css" href="~/app-assets/vendors/css/vendors.min.css" />
    <link rel="stylesheet" type="text/css" href="~/app-assets/vendors/css/extensions/toastr.css">
    <link rel="stylesheet" type="text/css" href="~/app-assets/vendors/css/tables/datatable/datatables.min.css">
    <link rel="stylesheet" type="text/css" href="~/app-assets/vendors/css/tables/datatable/responsive.dataTables.min.css">
    <link rel="stylesheet" type="text/css" href="~/app-assets/vendors/css/tables/datatable/rowReorder.dataTables.min.css">
    <link rel="stylesheet" type="text/css" href="~/app-assets/vendors/css/tables/ag-grid/ag-grid.css" />
    <link rel="stylesheet" type="text/css" href="~/app-assets/vendors/css/tables/ag-grid/ag-theme-material.css" />
    <link rel="stylesheet" type="text/css" href="~/app-assets/vendors/css/tables/datatable/extensions/dataTables.checkboxes.css">


    <!-- END: Vendor CSS-->
    <!-- BEGIN: Theme CSS-->
    <link rel="stylesheet" type="text/css" href="~/app-assets/css/bootstrap.css" />
    <link rel="stylesheet" type="text/css" href="~/app-assets/css/bootstrap-extended.css" />
    <link rel="stylesheet" type="text/css" href="~/app-assets/css/colors.css" />
    <link rel="stylesheet" type="text/css" href="~/app-assets/css/components.css" />
    <link rel="stylesheet" type="text/css" href="~/app-assets/css/themes/dark-layout.css" />
    <link rel="stylesheet" type="text/css" href="~/app-assets/css/themes/semi-dark-layout.css" />

    <!-- BEGIN: Page CSS-->
    <link rel="stylesheet" type="text/css" href="~/app-assets/css/plugins/extensions/toastr.css">
    <link rel="stylesheet" type="text/css" href="~/app-assets/css/core/menu/menu-types/vertical-menu.css">
    <link rel="stylesheet" type="text/css" href="~/app-assets/css/core/colors/palette-gradient.css">
    <link rel="stylesheet" type="text/css" href="~/app-assets/css/pages/app-user.css" />
    <link rel="stylesheet" type="text/css" href="~/app-assets/css/pages/aggrid.css" />
    <link rel="stylesheet" type="text/css" href="~/app-assets/css/plugins/file-uploaders/dropzone.css">
    <link rel="stylesheet" type="text/css" href="~/app-assets/css/pages/data-list-view.css">
    <!-- END: Page CSS-->
    <!-- BEGIN: Custom CSS-->
    <link rel="stylesheet" type="text/css" href="~/app-assets/css/custom-rtl.css" />
    <link rel="stylesheet" type="text/css" href="~/assets/scss/style.css" />
    }

    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
  @*  <link rel="stylesheet" href="~/Web.ERP.styles.css" asp-append-version="true" />*@
</head>

Web.ERP/Views/Shared/_Language.cshtml
@using Microsoft.AspNetCore.Localization;

@{
    var returnUrl = string.IsNullOrEmpty(Context.Request.Path) ? "~/" : $"~{Context.Request.Path.Value}";
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
}

@*.3yza ageb url 3ndna // ?? if path da rage3 b null rag3ny home page else hatly value bta3 path.*@

<form asp-controller="Languages" asp-action="SelectLanguage" asp-route-returnUrl="@returnUrl">

<li class="dropdown dropdown-language nav-item">

   @if(requestCulture!.RequestCulture.UICulture.Name == "ar")
            {
                 <a class="dropdown-toggle nav-link" id="dropdown-flag" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                 <i class="flag-icon flag-icon-sa"></i>
                 <span class="selected-language">Arabic</span>
                </a>
            }

            else
            {
                <a class="dropdown-toggle nav-link" id="dropdown-flag" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="flag-icon flag-icon-us"></i>
                    <span class="selected-language">English</span>
                </a>
    
            }

            
            <div class="dropdown-menu" aria-labelledby="dropdown-flag">

            <button class="dropdown-item" value="ar" name="culture" href="#" data-language="ar">
                 <i class="flag-icon flag-icon-sa"></i> Arabic
                 </button>

            <button class="dropdown-item" value="en" name="culture" href="#" data-language="en">
                 <i class="flag-icon flag-icon-us"></i> English
                 </button>

            </div>
</li>

    </form>